apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexacloud-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexacloud-api
  template:
    metadata:
      labels:
        app: nexacloud-api
    spec:
      containers:
      - name: api
        image: nexacloud-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
